Repository googleapis/gax-php, pull requests merged in 2020-10, with the labels that each got.

#284 fix: enable non-slash resource name seps [gax-php]
  src/ResourceTemplate/Parser.php
  tests/Tests/Unit/ResourceTemplate/ParserTest.php
Labels: cla: yes

#272 feat: default to self-signed JWTs and use updateMetadata for fetching tokens
  src/CredentialsWrapper.php
  src/GapicClientTrait.php
  src/Transport/GrpcTransport.php
  src/Transport/HttpUnaryTransportTrait.php
  tests/Tests/Unit/CredentialsWrapperTest.php
  tests/Tests/Unit/GapicClientTraitTest.php
  tests/Tests/Unit/Transport/GrpcTransportTest.php
  tests/Tests/Unit/Transport/RestTransportTest.php
Labels: cla: yes

#287 fix: Do not pass headers to credentials callback
  src/CredentialsWrapper.php
  src/Transport/HttpUnaryTransportTrait.php
  tests/Tests/Unit/Transport/RestTransportTest.php
Labels: cla: yes

#289 docs: add formatting steps to readme [gax-php]
  README.md
Labels: api: docs, cla: yes

#288 fix: Use non-slash separators when constructing relative PathTemplates [gax-php]
  src/ResourceTemplate/Parser.php
  src/ResourceTemplate/RelativeResourceTemplate.php
  src/ResourceTemplate/Segment.php
  tests/Tests/Unit/ResourceTemplate/ParserTest.php
  tests/Tests/Unit/ResourceTemplate/RelativeResourceTemplateTest.php
Labels: cla: yes

#286 chore: prepare 1.5.0
  VERSION
Labels: cla: yes

#290 chore: codeowners replace actools w/actools-php
  .github/CODEOWNERS
Labels: automerge, cla: yes

#281 chore: replace sami with doctum for doc generation
  .gitattributes
  .gitignore
  .travis.yml
  composer.json
  dev/sh/build-docs.sh
  dev/src/Docs/DoctumConfigBuilder.php
  dev/src/Docs/doctum-config.php
Labels: cla: yes

#291 feat: adds support for GAPICs to validate REST-only transports
  src/GapicClientTrait.php
  tests/Tests/Unit/GapicClientTraitTest.php
Labels: automerge, cla: yes, kokoro:force-run

#293 chore: update actools-php perms in sync settings
  .github/sync-repo-settings.yaml
Labels: cla: yes

#295 fix: add default audience to operations and paged methods
  src/GapicClientTrait.php
  tests/Tests/Unit/GapicClientTraitTest.php
Labels: cla: yes

#297 chore: prepare v1.6.0
  VERSION
Labels: cla: yes
